name: Update Files

on:
  push:
    branches:
      - main

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install

      - name: Run Scrap Script
        run: node scripts/scrap_ig.mjs

      - name: Commit Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Update files [skip ci]"
          git push





